version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:      
      - cqrs-networks

  rabbitmq:
    image: "rabbitmq:3-management"    
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:      
      - cqrs-networks

networks:
  cqrs-networks:
    driver: bridge

